name: Test Workflow

on:
  push:
    branches: [ main, master ]  # This will trigger on either branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test step
        run: echo "This is a test workflow"